server:
  port: 8001
spring:
  application:
    name: @project.artifactId@
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  servlet:
    multipart:
      max-file-size: 25MB
      max-request-size: 25MB
  data:
    mongodb:
      uri: mongodb://root:111111@sld-mongodb:27017/b2b2c
logging:
  file:
    name: /bbc/log/${spring.application.name}.log
  level:
    com.slodon.b2b2c: debug
slodon:
  b2b2c:
    datasource:
      write:
        url: jdbc:mysql://sld-mysql:3306/b2b2c?useUnicode=true&useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
      read:
        url: jdbc:mysql://sld-mysql:3306/b2b2c?useUnicode=true&useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai

socketio:

  # 客服模块socket配置
  im:
    host: 0.0.0.0	#监听的ip
    port: 8112		#监听端口
    # 设置最大每帧处理数据的长度，防止他人利用大数据来攻击服务器
    maxFramePayloadLength: 1048576
    # 设置http交互最大内容长度
    maxHttpContentLength: 1048576
    # socket连接数大小（如只监听一个端口boss线程组为1即可）
    bossCount: 1
    workCount: 100
    allowCustomRequests: true
    # 协议升级超时时间（毫秒），默认10秒。HTTP握手升级为ws协议超时时间
    upgradeTimeout: 1000000
    # Ping消息超时时间（毫秒），默认60秒，这个时间间隔内没有接收到心跳消息就会发送超时事件
    pingTimeout: 6000000
    # Ping消息间隔（毫秒），默认25秒。客户端向服务器发送一条心跳消息间隔
    pingInterval: 25000

secure:
  ignore:
    commonUrls: #不需要验证登录状态的url（不包含登录接口）
      - "/v3/captcha/**"
      - "/swagger-resources/**"
      - "/doc.html"
      - "/v2/api-docs"
      - "/*/*/v2/api-docs"
      - "/*/*/v2/api-docs-ext"
      - "/webjars/**"
      - "/favicon.ico"
      - "/v3/oss/**"
      - "/v3/msg/front/commons/getCaptcha"
      - "/v3/member/front/login/wechat/login"
      - "/v3/member/front/login/wechat/bindMobile"
      - "/v3/msg/front/commons/smsCode"
      - "/v3/member/front/login/wxjsConf"
      - "/v3/member/front/login/freeSecretLogin"
      - "/actuator/**"
      - "/v3/business/front/orderPayCallback/ali"
      - "/v3/business/front/orderPayCallback/wx"
      - "/v3/member/front/rechargeCallback/wx"
      - "/v3/member/front/rechargeCallback/ali"
      - "/v3/msg/seller/commons/smsCode"
      - "/v3/seller/seller/vendor/retrievePwd"
      - "/v3/seller/seller/vendor/register"
      - "/v3/seller/seller/registerPayCallback/**"
      - "/v3/seller/seller/renewPayCallback/**"
      - "/resources/**"
    login-urls: #登录接口
      - "/v3/frontLogin/**"
      - "/v3/adminLogin/**"
      - "/v3/sellerLogin/**"
    front-without-login-urls: #商城端不需要登录就可以访问的url
      - "/v3/goods/front/goods/details"
      - "/v3/goods/front/goods/goodsList"
      - "/v3/goods/front/goods/goodsBrandList"
      - "/v3/goods/front/goods/recommendList"
      - "/v3/goods/front/goods/share/sharePosters"
      - "/v3/goods/front/goods/category/list"
      - "/v3/goods/front/goods/category/screenList"
      - "/v3/goods/front/goods/comment"
      - "/v3/goods/front/goods/productInfo"
      - "/v3/goods/front/goods/newGoods"
      - "/v3/goods/front/goods/activityList"
      - "/v3/seller/front/store/list"
      - "/v3/seller/front/store/detail"
      - "/v3/seller/front/store/storeCategory"
      - "/v3/seller/front/storeCategory/list"
      - "/v3/member/front/productLookLog/add"
      - "/v3/member/front/memberPassword/resetLoginPwd"
      - "/v3/system/front/deco/index"
      - "/v3/system/front/deco/special"
      - "/v3/system/front/deco/storeIndex"
      - "/v3/system/front/deco/information"
      - "/v3/system/front/setting/getSettings"
      - "/v3/system/front/pcDeco/index"
      - "/v3/system/front/pcDeco/sellerIndex"
      - "/v3/system/front/deco/firstAdv"
      - "/v3/system/front/navigation/list"
      - "/v3/system/front/agreement/detail"
      - "/v3/system/admin/search/esInit"
      - "/v3/frontLogin/oauth/register"
      - "/v3/promotion/front/coupon/storeCouponList"
      - "/v3/promotion/front/coupon/couponCenter"
      - "/v3/promotion/front/seckill/getSeckillLabel"
      - "/v3/promotion/front/seckill/getSeckillStage"
      - "/v3/promotion/front/seckill/goodsList"
      - "/v3/promotion/front/seckill/banner"
      - "/v3/promotion/front/draw/detail"
      - "/v3/promotion/front/draw/integral"
      - "/v3/promotion/front/preSell/list"
      - "/v3/promotion/front/preSell/detail"
      - "/v3/cms/front/friendLink/list"
      - "/v3/cms/front/article/helpList"
      - "/v3/cms/front/article/articleList"
      - "/v3/cms/front/article/articleDetail"
      - "/v3/cms/front/information/list"
      - "/v3/cms/front/info/detail"
      - "/v3/cms/front/information/cateList"
      - "/v3/integral/front/integral/mall/list"
      - "/v3/integral/front/integral/mall/goodsList"
      - "/v3/integral/front/integral/mall/recommendList"
      - "/v3/integral/front/integral/mall/details"
      - "/v3/business/seller/faceSheet/generate"
      - "/v3/system/seller/setting/getStoreSetting"
      - "/v3/system/admin/setting/getPcMainImage"
